### ISSUE TITLE
Clarification for the "Add type aliases" exercise

### ISSUE THREAD

**Issue by imteekay** [sandersn/mini-typescript#17]
Hey! I'm working on the next exercise for the mini-typescript and it's the "Add type aliases" one.
But I'm not sure if it's already implemented.
- The lexer already creates `Type` token
- The parser already parses the `Type` token and creates the `TypeAlias` ast node
- The binder assigns the type alias into the symbols table and the compiler can reference to it later in the program
- And the checker checks the type based on the `typename`

What should I do next in this exercise, @sandersn? Thank you!

**Comment by sandersn** [comment]
Hah, you're right. As a follow-up you could consider adding `interface` support, which requires both `type` and `interface` to be treated (nearly) the same -- something that the code currently does not support. It would be quite similar to adding both `var` and `let`.

**Comment by sandersn** [comment]
Done
